### ISSUE TITLE
请问支不支持使用python调用进行批量下载？

### ISSUE THREAD

**Issue by FateRui** [iawia002/Lulu#105]
事情是这样的，我这个人嫌麻烦，一个链接一个链接下载觉得太麻烦了，请问能不能使用python进行调用批量下载？

**Comment by iawia002** [comment]
> Unmaintained
> For a similar project that is still actively developed, try Annie: https://github.com/iawia002/annie

https://github.com/iawia002/annie#multiple-inputs
