### ISSUE TITLE
请更新吧，软件不能使用了

### ISSUE THREAD

**Issue by Alse2893** [iawia002/Lulu#106]
请更新一下吧，现在下载B站或者西瓜视频已经出现错误无法下载了！
出错截图：
![lulu](https://user-images.githubusercontent.com/40057514/41149709-dd4fe6ee-6b3e-11e8-8c16-de7ec12f0df1.JPG)

**Comment by iawia002** [comment]
> Unmaintained
> For a similar project that is still actively developed, try Annie: https://github.com/iawia002/annie

https://github.com/iawia002/annie
