### ISSUE TITLE
无法正确解析bilibili的playlist

### ISSUE THREAD

**Issue by XDcedar** [iawia002/Lulu#109]
使用
`lulu --playlist bilibili_url/av../`
下载下来的视频始终的part 1

如果用
`lulu bilibili_url/av../?p=2`
解析到的还是part 1

**Comment by Z4HD** [comment]
项目早已停止维护，详见`README.md`。

您也可以考虑试试作者的另一个项目[Annie](https://github.com/iawia002/annie)。
