### ISSUE TITLE
哥们不错啊，可否把B站的解析单独抽离一个脚本出来？

### ISSUE THREAD

**Issue by tonyxyl** [iawia002/Lulu#17]
you-get项目组太不思进取了，b站都解析失败很久了还没解决。

**Comment by iawia002** [comment]
单独抽离出来是指写个新工具只支持 B 站？这样太麻烦了吧，毕竟实现完整下载不只解析，还有其他很多东西。现在 lulu 是解决了 B 站的问题的，你还遇到什么问题吗

**Comment by Z4HD** [comment]
Lulu在某种意义上就是修复了B站视频下载问题的you-get，你或许可以把它理解为“_把B站的解析单独抽离一个脚本出来_”
