### ISSUE TITLE
iqiyi这种方式实在不想用

### ISSUE THREAD

**Issue by hobmgcode** [iawia002/Lulu#53]
这是当初放弃you-get 的原因

**Comment by hobmgcode** [comment]
和油猴+idm比优势在哪里？

**Comment by iawia002** [comment]
明天或者后天修复，我把它改成用 lulu 下载，最后用 ffmpeg 来合并

**Comment by iawia002** [comment]
related issue: #44 
related issue: #48

**Comment by iawia002** [comment]
@hobmgcode @macdavis  更新一下 0.3.3
