### ISSUE TITLE
建议：分段过多的能否同时下载多个分段？

### ISSUE THREAD

**Issue by note286** [iawia002/Lulu#65]
例如芒果tv的快乐大本营，lulu --format=sd https://www.mgtv.com/b/320519/4287283.html

有529个分段，每个分段下载的时候都不能把带宽跑满，(只有100多k的速度，但实际上我的带宽可以达到4M的)，能不能实现同时下载多个分段，这样速度是不是就可以成倍的增加。

希望作者考虑一下，非常感谢！

**Comment by iawia002** [comment]
现在有两个提升点：

* 本来有多个分段的视频，多线程/进程同时下载，每个线程/进程下载一个分段
* 本来就一个视频文件，对这一个文件也多线程/进程同时下载

我的想法是现在第一条很必要，第二条暂不考虑

**Comment by iawia002** [comment]
会考虑的

**Comment by iawia002** [comment]
现在有两个提升点：

* 本来有多个分段的视频，多线程/进程同时下载，每个线程/进程下载一个分段
* 本来就一个视频文件，对这一个文件也多线程/进程同时下载

我的想法是现在第一条有必要，第二条暂不考虑

**Comment by note286** [comment]
@iawia002 我代码写的不多，我个人也认为第一个是必须的，而且应该编码方面会容易很多，希望尽快添加，毕竟每周一集的快本只有芒果tv有，哈哈哈，非常感谢作者的工作。

**Comment by Justsoos** [comment]
其实 ts 结构是流媒体播放为了减少客户端延时，所以切成了几百几千小碎文件。这东西并不是为了用来并行下载的 …… 个人可以这么用，但很容易招致流媒体服务网站不满，甚至封杀，减速。
而且对直播来说，这东西没啥用。
多数情况下，ts 下载速度慢，是因为文件小而碎，导致网络和文件系统对话成本高。

**Comment by note286** [comment]
@iawia002 确定多线程参数可以？？
```
lulu --thread 2 "https://www.mgtv.com/b/320519/4287283.html"
usage: lulu [OPTION]... URL...
lulu: error: unrecognized arguments: --thread
```

**Comment by iawia002** [comment]
我还没发版本

**Comment by iawia002** [comment]
@note286 可以了

**Comment by Justsoos** [comment]
等着看你 @note286 的 286 电脑下载500 多小文件，再次消失 （ 手动哈哈

**Comment by note286** [comment]
@iawia002 速度非常快，感谢！

**Comment by note286** [comment]
@Justsoos 还真让你说对了，哈哈哈，还真消失了，神奇！我把remove注释掉再用吧，不是很影响。

**Comment by Justsoos** [comment]
mgtv 这网站的技术和产品不太靠谱的，他们能出错，不奇怪。不过你可以用 youtube-dl 重新试试，如果能下载，说明 you-get 底层也不靠谱。哈
