### ISSUE TITLE
lulu下载B站的视频时候有问题

### ISSUE THREAD

**Issue by LuGuoHuas** [iawia002/Lulu#85]
lulu --debug https://www.bilibili.com/bangumi/play/ep173294
下载 京紫的时候报错.是怎么回事?不能下吗

`[DEBUG] get_content: https://www.bilibili.com/bangumi/play/ep173294
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=116&quality=116&ts=1520587124&sign=00cec43b9e93bc372b641227c858c2a5
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=74&quality=74&ts=1520587125&sign=d21b810842a1a6f2e80345bbb44aafba
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=80&quality=80&ts=1520587125&sign=212cb4cc01b35f69ab708d036544ecc5
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=64&quality=64&ts=1520587125&sign=4a8a8a2065beb9055f087ad180fa276b
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=32&quality=32&ts=1520587125&sign=fcbe65d587bf6aaeca6f42cc9ed9aa4c
[DEBUG] get_content: https://bangumi.bilibili.com/player/web_api/playurl?cid=33480964&module=bangumi&player=1&qn=15&quality=15&ts=1520587125&sign=ad85f8c87bcf80c4ff2b18728a3dc92a
[DEBUG] get_content: https://comment.bilibili.com/33480964.xml
lulu: version 0.4.9, a tiny downloader that scrapes the web.
lulu: Namespace(URL=['https://www.bilibili.com/bangumi/play/ep173294'], cookies=None, debug=True, extractor_proxy=None, force=False, format=None, help=False, http_proxy=None, info=False, input_file=None, itag=None, json=False, no_caption=False, no_merge=False, no_proxy=False, output_dir='.', output_filename=None, password=None, player=None, playlist=False, socks_proxy=None, stream=None, thread=0, timeout=600, url=False, version=False)
Traceback (most recent call last):
  File "/usr/bin/lulu", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/lulu/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/common.py", line 1419, in main
    script_main(any_download, any_download_playlist, **kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/common.py", line 1309, in script_main
    **extra
  File "/usr/lib/python3.6/site-packages/lulu/common.py", line 1047, in download_main
    download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/common.py", line 1410, in any_download
    m.download(url, **kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/extractor.py", line 78, in download_by_url
    self._prepare_download(**kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/extractor.py", line 73, in _prepare_download
    self.download(**kwargs)
  File "/usr/lib/python3.6/site-packages/lulu/extractor.py", line 223, in download
    if 'id' in self.streams_sorted[0] \
IndexError: list index out of range
`

**Comment by iawia002** [comment]
@LuGuoHuas 这是个 bug，我晚上看看，你可以试试 <https://github.com/iawia002/annie>，B 站下载是支持的，比 lulu 快

**Comment by iawia002** [comment]
@LuGuoHuas 这不是 bug，你这个第 9 集是大会员付费才能看的呀

**Comment by iawia002** [comment]
如果你有大会员的话，可以用大会员账号请求的 cookies 来下载这种视频
