### ISSUE TITLE
无法识别相应的url

### ISSUE THREAD

**Issue by happened** [iawia002/Lulu#98]
在下载bilibili多P的视频中，貌似url不同下载下来的仍然是第一个视频。
例：
lulu --format=flv720 -T 4  -O D://Bilibili//network//13.OSI参考模型（1） https://www.bilibili.com/video/av19786297/?p=13
lulu --format=flv720 -T 4  -O D://Bilibili//network//14.OSI参考模型（2） https://www.bilibili.com/video/av19786297/?p=14
这两句分别下载不同的视频，可是在下载的时候却是
lulu --format=flv720 -T 4  -O D://Bilibili//network//1.概述 https://www.bilibili.com/video/av19786297/?p=1这一句所下载的视频。
更换url貌似没啥用

**Comment by happened** [comment]
搞定了，下载多p视频那个url不是浏览器上那个，得改
https://www.bilibili.com/video/av19786297/index_6.html#page=6
将url改掉就行了，然后写个bat就可以批量保存为不同文件了。

**Comment by iawia002** [comment]
B 站的播放列表页面结构变了，lulu 没有更新，还有这个项目不再维护了，我在 README 里面写了的

> Unmaintained
> Sorry for this.
> For a similar project that is still actively developed, try Annie: https://github.com/iawia002/annie

**Comment by iawia002** [comment]
有兴趣的话可以试试 https://github.com/iawia002/annie
这个下播放列表没问题
